Update integration-test.yml

diff --git a/.github/workflows/integration-test.yml b/.github/workflows/integration-test.yml
--- a/.github/workflows/integration-test.yml
+++ b/.github/workflows/integration-test.yml
@@ -1,5 +1,4 @@
-# This workflow will build a golang project
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
+# .github/workflows/docker-integration-test.yml
 
 name: Docker Integration Test
 
@@ -28,7 +27,6 @@ jobs:
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       DAPP_TESTS_MNEMONIC: ${{ secrets.DAPP_TESTS_MNEMONIC }}
     strategy:
-      # other jobs should run even if one integration test fails
       fail-fast: false
       matrix:
         test: [
@@ -66,8 +64,8 @@ jobs:
           {
             name: "Chain Operation Test",
             scripts: [
-              "until [ $(cat build/generated/rpc-launch.complete |wc -l) = 1 ]; do sleep 10; done",
-              "until [[ $(docker exec sei-rpc-node build/seid status |jq -M -r .SyncInfo.latest_block_height) -gt 10 ]]; do sleep 10; done",
+              "until [ $(cat build/generated/rpc-launch.complete | wc -l) = 1 ]; do sleep 10; done",
+              "until [[ $(docker exec sei-rpc-node build/seid status | jq -M -r .SyncInfo.latest_block_height) -gt 10 ]]; do sleep 10; done",
               "echo rpc node started",
               "python3 integration_test/scripts/runner.py integration_test/chain_operation/snapshot_operation.yaml",
               "python3 integration_test/scripts/runner.py integration_test/chain_operation/statesync_operation.yaml"
@@ -77,7 +75,7 @@ jobs:
             name: "Distribution Module",
             scripts: [
               "python3 integration_test/scripts/runner.py integration_test/distribution_module/community_pool.yaml",
-              "python3 integration_test/scripts/runner.py integration_test/distribution_module/rewards.yaml",
+              "python3 integration_test/scripts/runner.py integration_test/distribution_module/rewards.yaml"
             ]
           },
           {
@@ -99,21 +97,13 @@ jobs:
             scripts: [
               "docker exec sei-node-0 integration_test/contracts/deploy_wasm_contracts.sh",
               "docker exec sei-node-0 integration_test/contracts/create_tokenfactory_denoms.sh",
-              "python3 integration_test/scripts/runner.py integration_test/seidb/state_store_test.yaml",
-            ],
-          },
-          {
-            name: "SeiDB State Store",
-            scripts: [
-              "docker exec sei-node-0 integration_test/contracts/deploy_wasm_contracts.sh",
-              "docker exec sei-node-0 integration_test/contracts/create_tokenfactory_denoms.sh",
-              "python3 integration_test/scripts/runner.py integration_test/seidb/state_store_test.yaml",
+              "python3 integration_test/scripts/runner.py integration_test/seidb/state_store_test.yaml"
             ]
           },
           {
             name: "EVM Module",
             scripts: [
-              "./integration_test/evm_module/scripts/evm_tests.sh",
+              "./integration_test/evm_module/scripts/evm_tests.sh"
             ]
           },
           {
@@ -127,56 +117,56 @@ jobs:
             scripts: [
               "./integration_test/dapp_tests/dapp_tests.sh seilocal"
             ]
-          },
+          }
         ]
+
     steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-python@v4
+      - name: 🧾 Checkout repo
+        uses: actions/checkout@v3
+
+      - name: 🐍 Set up Python
+        uses: actions/setup-python@v4
         with:
           python-version: '3.10'
-      - uses: actions/setup-node@v2
+
+      - name: 🧰 Set up Node.js
+        uses: actions/setup-node@v2
         with:
           node-version: '20'
 
-      - name: Pyyaml
-        run: |
-          pip3 install pyyaml
+      - name: 🧩 Install Python deps
+        run: pip3 install pyyaml
 
-      - name: Install jq
+      - name: 🧩 Install jq
         run: sudo apt-get install -y jq
 
-      - name: Set up Go
+      - name: 🧪 Set up Go
         uses: actions/setup-go@v3
         with:
           go-version: 1.21
 
-      - name: Start 4 node docker cluster
+      - name: 🐳 Start 4-node docker cluster
         run: make clean && INVARIANT_CHECK_INTERVAL=10 ${{matrix.test.env}} make docker-cluster-start &
 
-      - name: Wait for docker cluster to start
+      - name: ⏳ Wait for cluster
         run: |
-          until [ $(cat build/generated/launch.complete |wc -l) = 4 ]
-          do
-            sleep 10
-          done
+          until [ $(cat build/generated/launch.complete | wc -l) = 4 ]; do sleep 10; done
           sleep 10
 
-      - name: Start rpc node
+      - name: 🚀 Start rpc node
         run: make run-rpc-node-skipbuild &
 
-      - name: Verify Sei Chain is running
+      - name: ✅ Verify startup
         run: python3 integration_test/scripts/runner.py integration_test/startup/startup_test.yaml
 
-      - name: ${{ matrix.test.name }}
+      - name: 🔁 Run ${{ matrix.test.name }}
         run: |
           scripts=$(echo '${{ toJson(matrix.test.scripts) }}' | jq -r '.[]')
-          IFS=$'\n'   # change the internal field separator to newline
-          echo $scripts
-          for script in $scripts
-          do
+          IFS=$'\n'
+          for script in $scripts; do
             bash -c "${script}"
           done
-          unset IFS  # revert the internal field separator back to default
+          unset IFS
 
   integration-test-check:
     name: Integration Test Check
@@ -184,7 +174,7 @@ jobs:
     needs: integration-tests
     if: always()
     steps:
-      - name: Get workflow conclusion
+      - name: 📋 Check test result status
         id: workflow_conclusion
         uses: nick-fields/retry@v2
         with:
@@ -192,20 +182,13 @@ jobs:
           retry_on: error
           timeout_seconds: 30
           command: |
-              jobs=$(curl https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs)
-              job_statuses=$(echo "$jobs" | jq -r '.jobs[] | .conclusion')
-
-              for status in $job_statuses
-              do
-                echo "Status: $status"
-                if [[ "$status" == "failure" ]]; then
-                  echo "Some or all tests have failed!"
-                  exit 1
-                fi
-                if [[ "$status" == "cancelled" ]]; then
-                  echo "Some or all tests have been cancelled!"
-                  exit 1
-                fi
-              done
-
-              echo "All tests have passed!"
+            jobs=$(curl -s https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs)
+            job_statuses=$(echo "$jobs" | jq -r '.jobs[] | .conclusion')
+            for status in $job_statuses; do
+              echo "Status: $status"
+              if [[ "$status" == "failure" || "$status" == "cancelled" ]]; then
+                echo "Some or all tests failed or were cancelled."
+                exit 1
+              fi
+            done
+            echo "✅ All tests passed!"
